language: python
python:
  -"3.7" # version of stable python in travis channel

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"